# Generated by Django 5.0.6 on 2024-09-29 20:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCloudServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('position', models.IntegerField(null=True)),
                ('url', models.URLField(null=True)),
                ('image', models.CharField(max_length=2048, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=64)),
            ],
            options={
                'db_table': 'core_cloud_service_provider',
            },
        ),
        migrations.CreateModel(
            name='CoreAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Suspended')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'core_account',
            },
        ),
        migrations.CreateModel(
            name='CoreCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('delete', 'Delete')], default='active', max_length=64)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.coreaccount')),
            ],
            options={
                'db_table': 'core_cloud',
            },
        ),
        migrations.CreateModel(
            name='CoreMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_members', to='apps.coreaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'core_member',
            },
        ),
        migrations.CreateModel(
            name='CoreAccountMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'Member'), (1, 'Admin'), (2, 'Owner')], default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.coreaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.coremember')),
            ],
            options={
                'db_table': 'core_account_membership',
                'unique_together': {('account', 'member')},
            },
        ),
        migrations.AddField(
            model_name='coreaccount',
            name='members',
            field=models.ManyToManyField(related_name='accounts', through='apps.CoreAccountMembership', to='apps.coremember'),
        ),
        migrations.CreateModel(
            name='CoreNotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=256)),
                ('status', models.IntegerField(choices=[(0, 'Un-Verified'), (1, 'Verified'), (2, 'Hard bounce'), (3, 'Spam complaint')], default=0)),
                ('verify_code', models.CharField(max_length=256, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_email', to='apps.coremember')),
            ],
            options={
                'db_table': 'core_notification_email',
            },
        ),
        migrations.CreateModel(
            name='CoreNotificationLogEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(editable=False, max_length=254)),
                ('text_body', models.TextField(editable=False, null=True)),
                ('html_body', models.TextField(editable=False, null=True)),
                ('subject', models.TextField(editable=False, null=True)),
                ('context', models.JSONField(editable=False, null=True)),
                ('template', models.CharField(max_length=1024, null=True)),
                ('message_id', models.CharField(max_length=1024, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_log_email', to='apps.coremember')),
            ],
            options={
                'db_table': 'core_notification_log_email',
            },
        ),
        migrations.CreateModel(
            name='DigitalOceanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('access_token', models.CharField(max_length=255)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitalocean', to='apps.corecloud')),
            ],
            options={
                'db_table': 'core_digitalocean_account',
            },
        ),
        migrations.CreateModel(
            name='DigitalOceanDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='apps.digitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_database',
            },
        ),
        migrations.CreateModel(
            name='DigitalOceanServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='apps.digitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_server',
            },
        ),
        migrations.CreateModel(
            name='DigitalOceanVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='apps.digitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_volume',
            },
        ),
        migrations.AddConstraint(
            model_name='corenotificationemail',
            constraint=models.UniqueConstraint(fields=('member', 'email'), name='unique_account_notification'),
        ),
    ]
