# Generated by Django 5.0.6 on 2024-09-29 20:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DigitalOceanDatabase',
            new_name='CoreDigitalOceanDatabase',
        ),
        migrations.RenameModel(
            old_name='DigitalOceanServer',
            new_name='CoreDigitalOceanServer',
        ),
        migrations.RenameModel(
            old_name='DigitalOceanVolume',
            new_name='CoreDigitalOceanVolume',
        ),
        migrations.RenameModel(
            old_name='DigitalOceanAccount',
            new_name='CoreDigitalOceanAccount',
        ),
    ]
