# Generated by Django 5.0.6 on 2024-09-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_digitaloceandatabase_coredigitaloceandatabase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredigitaloceanaccount',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=64),
        ),
    ]
