# Generated by Django 5.0.6 on 2024-09-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_coredigitaloceanaccount_last_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecloud',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clouds', to='apps.corecloudserviceprovider'),
            preserve_default=False,
        ),
    ]
