# Generated by Django 5.0.6 on 2024-09-30 10:08

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_corecloud_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreHetznerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=64)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('access_token', models.CharField(max_length=255)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hetzner', to='apps.corecloud')),
            ],
            options={
                'db_table': 'core_hetzner_account',
            },
        ),
        migrations.CreateModel(
            name='CoreHetznerDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='apps.corehetzneraccount')),
            ],
            options={
                'db_table': 'core_hetzner_database',
            },
        ),
        migrations.CreateModel(
            name='CoreHetznerServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='apps.corehetzneraccount')),
            ],
            options={
                'db_table': 'core_hetzner_server',
            },
        ),
        migrations.CreateModel(
            name='CoreHetznerVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='apps.corehetzneraccount')),
            ],
            options={
                'db_table': 'core_hetzner_volume',
            },
        ),
    ]
