# Generated by Django 5.0.6 on 2024-09-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_corehetzneraccount_corehetznerdatabase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corehetzneraccount',
            name='access_token',
        ),
        migrations.AddField(
            model_name='corehetzneraccount',
            name='api_token',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
