# Generated by Django 5.0.6 on 2024-09-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_corehetzneraccount_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredigitaloceandatabase',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserver',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolume',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AddField(
            model_name='corehetznerserver',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AddField(
            model_name='corehetznervolume',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='corehetzneraccount',
            name='api_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.DeleteModel(
            name='CoreHetznerDatabase',
        ),
    ]
