# Generated by Django 5.0.6 on 2024-09-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_corevultraccount_corevultrdatabase_corevultrserver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredigitaloceandatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='corehetznerserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='corehetznervolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='corevultrdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='corevultrserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='corevultrvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True),
        ),
    ]
