# Generated by Django 5.0.6 on 2024-10-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_coredigitaloceandatabase_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coredigitaloceandatabase',
            old_name='status',
            new_name='monitoring',
        ),
        migrations.RenameField(
            model_name='coredigitaloceanserver',
            old_name='status',
            new_name='monitoring',
        ),
        migrations.RenameField(
            model_name='coredigitaloceanvolume',
            old_name='status',
            new_name='monitoring',
        ),
        migrations.RenameField(
            model_name='corehetznerserver',
            old_name='status',
            new_name='monitoring',
        ),
        migrations.RenameField(
            model_name='corehetznervolume',
            old_name='status',
            new_name='monitoring',
        ),
        migrations.RenameField(
            model_name='corevultrdatabase',
            old_name='status',
            new_name='monitoring',
        ),
        migrations.RenameField(
            model_name='corevultrserver',
            old_name='status',
            new_name='monitoring',
        ),
        migrations.RenameField(
            model_name='corevultrvolume',
            old_name='status',
            new_name='monitoring',
        ),
    ]
