# Generated by Django 5.0.6 on 2024-10-05 12:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_rename_status_coredigitaloceandatabase_monitoring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('cron', 'Cron'), ('rate', 'Rate'), ('at', 'One-time')], default='cron', max_length=64)),
                ('rate_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], max_length=64, null=True)),
                ('rate_value', models.IntegerField(null=True)),
                ('at_datetime', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('hour', models.CharField(blank=True, max_length=255, null=True)),
                ('minute', models.CharField(blank=True, max_length=255, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=255, null=True)),
                ('day_of_month', models.CharField(blank=True, max_length=255, null=True)),
                ('month_of_year', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, default='*', max_length=255, null=True)),
                ('aws_schedule_arn', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_schedule',
            },
        ),
        migrations.RemoveField(
            model_name='corevultrserver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='corevultrvolume',
            name='name',
        ),
        migrations.AddField(
            model_name='coredigitaloceandatabase',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corehetznerserver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corehetznervolume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corevultrdatabase',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corevultrserver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corevultrvolume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
    ]
