# Generated by Django 5.0.6 on 2024-10-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_coreschedule_remove_corevultrserver_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coredigitaloceandatabase',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceanserver',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceanvolume',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corehetznerserver',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corehetznervolume',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corevultrdatabase',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corevultrserver',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corevultrvolume',
            name='schedule',
        ),
    ]
