# Generated by Django 5.0.6 on 2024-10-05 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_remove_coredigitaloceandatabase_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredigitaloceandatabase',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corehetznerserver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corehetznervolume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corevultrdatabase',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corevultrserver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
        migrations.AddField(
            model_name='corevultrvolume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.coreschedule'),
        ),
    ]
