# Generated by Django 5.0.6 on 2024-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_coredigitaloceandatabase_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corehetzneraccount',
            name='api_token',
        ),
        migrations.AddField(
            model_name='corecloudserviceprovider',
            name='aws_lambda_arn',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
