# Generated by Django 5.0.6 on 2024-10-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_remove_corehetzneraccount_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecloudserviceprovider',
            name='aws_role_arn',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
