# Generated by Django 5.0.6 on 2024-10-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_corecloudserviceprovider_aws_role_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreschedule',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
