# Generated by Django 5.0.6 on 2024-10-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_coreschedule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='corehetzneraccount',
            name='api_token',
            field=models.CharField(default='aaa', max_length=1024),
            preserve_default=False,
        ),
    ]
