# Generated by Django 5.0.6 on 2024-10-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_corehetzneraccount_api_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corehetzneraccount',
            old_name='api_token',
            new_name='access_token',
        ),
    ]
