# Generated by Django 5.0.6 on 2024-10-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_rename_api_token_corehetzneraccount_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecloudserviceprovider',
            name='aws_lambda_database_arn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='corecloudserviceprovider',
            name='aws_lambda_server_arn',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='corecloudserviceprovider',
            name='aws_lambda_volume_arn',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
