# Generated by Django 5.0.6 on 2024-10-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_corecloudserviceprovider_aws_lambda_database_arn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corecloudserviceprovider',
            name='aws_lambda_arn',
        ),
        migrations.AddField(
            model_name='coredigitaloceandatabase',
            name='status_timeline',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserver',
            name='status_timeline',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolume',
            name='status_timeline',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corehetznerserver',
            name='status_timeline',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corehetznervolume',
            name='status_timeline',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corevultrdatabase',
            name='status_timeline',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corevultrserver',
            name='status_timeline',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corevultrvolume',
            name='status_timeline',
            field=models.JSONField(null=True),
        ),
    ]
