# Generated by Django 5.0.6 on 2024-10-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_remove_corecloudserviceprovider_aws_lambda_arn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coredigitaloceandatabase',
            name='status_timeline',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceanserver',
            name='status_timeline',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceanvolume',
            name='status_timeline',
        ),
        migrations.RemoveField(
            model_name='corehetznerserver',
            name='status_timeline',
        ),
        migrations.RemoveField(
            model_name='corehetznervolume',
            name='status_timeline',
        ),
        migrations.RemoveField(
            model_name='corevultrdatabase',
            name='status_timeline',
        ),
        migrations.RemoveField(
            model_name='corevultrserver',
            name='status_timeline',
        ),
        migrations.RemoveField(
            model_name='corevultrvolume',
            name='status_timeline',
        ),
    ]
