# Generated by Django 5.1.2 on 2024-10-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_remove_coredigitaloceandatabase_status_timeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coredigitaloceandatabase',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule'),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanserver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule'),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanvolume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule'),
        ),
        migrations.AlterField(
            model_name='corehetznerserver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule'),
        ),
        migrations.AlterField(
            model_name='corehetznervolume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule'),
        ),
        migrations.AlterField(
            model_name='corevultrdatabase',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule'),
        ),
        migrations.AlterField(
            model_name='corevultrserver',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule'),
        ),
        migrations.AlterField(
            model_name='corevultrvolume',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule'),
        ),
    ]
