# Generated by Django 5.1.2 on 2024-10-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_alter_coredigitaloceandatabase_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waiting List Entry',
                'verbose_name_plural': 'Waiting List Entries',
                'db_table': 'core_waiting_list',
            },
        ),
    ]
