# Generated by Django 5.1.2 on 2024-10-18 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_waitinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreaccountmembership',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='apps.coreaccount'),
        ),
        migrations.AlterField(
            model_name='coreaccountmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='apps.coremember'),
        ),
    ]
