# Generated by Django 5.1.2 on 2024-11-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_alter_coreaccountmembership_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corevultrserver',
            name='name',
            field=models.CharField(default='cloud server', max_length=100),
            preserve_default=False,
        ),
    ]
