# Generated by Django 5.1.2 on 2024-11-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_corevultrserver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='corevultrvolume',
            name='name',
            field=models.CharField(default='Cloud Volume', max_length=100),
            preserve_default=False,
        ),
    ]
