# Generated by Django 5.1.4 on 2024-12-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_corevultrdatabaselog_corevultrserverlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corecloudserviceprovider',
            name='aws_lambda_database_arn',
        ),
        migrations.RemoveField(
            model_name='corecloudserviceprovider',
            name='aws_lambda_server_arn',
        ),
        migrations.RemoveField(
            model_name='corecloudserviceprovider',
            name='aws_lambda_volume_arn',
        ),
        migrations.RemoveField(
            model_name='corecloudserviceprovider',
            name='aws_role_arn',
        ),
    ]
