# Generated by Django 5.1.4 on 2024-12-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_remove_corecloudserviceprovider_aws_lambda_database_arn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredigitaloceandatabaselog',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceandatabaselog',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserverlog',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserverlog',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolumelog',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolumelog',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corehetznerserverlog',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corehetznerserverlog',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corehetznervolumelog',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corehetznervolumelog',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corevultrdatabaselog',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corevultrdatabaselog',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corevultrserverlog',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corevultrserverlog',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='corevultrvolumelog',
            name='error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='corevultrvolumelog',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
