# Generated by Django 5.1.4 on 2024-12-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_coredigitaloceandatabaselog_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredigitaloceandatabase',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserver',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolume',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AddField(
            model_name='corehetznerserver',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AddField(
            model_name='corehetznervolume',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AddField(
            model_name='corevultrdatabase',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AddField(
            model_name='corevultrserver',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AddField(
            model_name='corevultrvolume',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
    ]
