# Generated by Django 5.1.4 on 2024-12-21 17:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_coredigitaloceandatabase_notification_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreDigitalOceanDatabaseEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apps.coredigitaloceandatabase')),
            ],
            options={
                'db_table': 'core_digitalocean_database_email',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanServerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apps.coredigitaloceanserver')),
            ],
            options={
                'db_table': 'core_digitalocean_server_email',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanVolumeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apps.coredigitaloceanvolumelog')),
            ],
            options={
                'db_table': 'core_digitalocean_volume_email',
            },
        ),
        migrations.CreateModel(
            name='CoreHetznerServerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apps.corehetznerserver')),
            ],
            options={
                'db_table': 'core_hetzner_server_email',
            },
        ),
        migrations.CreateModel(
            name='CoreHetznerVolumeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apps.corehetznervolume')),
            ],
            options={
                'db_table': 'core_hetzner_volume_email',
            },
        ),
        migrations.CreateModel(
            name='CoreVultrDatabaseEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apps.corevultrdatabase')),
            ],
            options={
                'db_table': 'core_vultr_database_email',
            },
        ),
        migrations.CreateModel(
            name='CoreVultrServerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apps.corevultrserver')),
            ],
            options={
                'db_table': 'core_vultr_server_email',
            },
        ),
        migrations.CreateModel(
            name='CoreVultrVolumeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(null=True)),
                ('html', models.TextField(null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='apps.corevultrvolume')),
            ],
            options={
                'db_table': 'core_vultr_volume_email',
            },
        ),
    ]
