# Generated by Django 5.1.4 on 2024-12-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_coredigitaloceandatabaseemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corenotificationlogemail',
            name='member',
        ),
        migrations.DeleteModel(
            name='CoreNotificationEmail',
        ),
        migrations.DeleteModel(
            name='CoreNotificationLogEmail',
        ),
    ]
