# Generated by Django 5.1.4 on 2024-12-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_remove_corenotificationlogemail_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredigitaloceanaccount',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corehetzneraccount',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corevultraccount',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
