# Generated by Django 5.1.4 on 2024-12-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_coredigitaloceanaccount_aws_schedule_arn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coredigitaloceanaccount',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corehetzneraccount',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corevultraccount',
            name='aws_schedule_arn',
        ),
        migrations.AddField(
            model_name='corecloud',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
