# Generated by Django 5.1.5 on 2025-02-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_remove_coredigitaloceanaccount_aws_schedule_arn_and_more'),
    ]

    sql = """
                CREATE OR REPLACE FUNCTION get_asset_timeline(
                    p_asset_table text,
                    p_asset_id integer,
                    p_start_date timestamp with time zone,
                    p_end_date timestamp with time zone
                )
                RETURNS TABLE (
                    status_value text,
                    event_timestamp timestamp with time zone,
                    time_duration interval
                ) AS $$
                BEGIN
                    RETURN QUERY
                    WITH status_logs AS (
                        SELECT status::text, created
                        FROM (
                            SELECT status::text, created
                            FROM core_digitalocean_server_log 
                            WHERE asset_id = p_asset_id AND p_asset_table = 'core_digitalocean_server'
                            UNION ALL
                            SELECT status::text, created
                            FROM core_digitalocean_volume_log 
                            WHERE asset_id = p_asset_id AND p_asset_table = 'core_digitalocean_volume'
                            UNION ALL
                            SELECT status::text, created
                            FROM core_digitalocean_database_log 
                            WHERE asset_id = p_asset_id AND p_asset_table = 'core_digitalocean_database'
                            UNION ALL
                            SELECT status::text, created
                            FROM core_hetzner_server_log 
                            WHERE asset_id = p_asset_id AND p_asset_table = 'core_hetzner_server'
                            UNION ALL
                            SELECT status::text, created
                            FROM core_hetzner_volume_log 
                            WHERE asset_id = p_asset_id AND p_asset_table = 'core_hetzner_volume'
                            UNION ALL
                            SELECT status::text, created
                            FROM core_vultr_server_log 
                            WHERE asset_id = p_asset_id AND p_asset_table = 'core_vultr_server'
                            UNION ALL
                            SELECT status::text, created
                            FROM core_vultr_volume_log 
                            WHERE asset_id = p_asset_id AND p_asset_table = 'core_vultr_volume'
                        ) AS log_data
                        WHERE created BETWEEN p_start_date AND p_end_date
                        AND status != 'error'
                    ),
                    status_with_prev AS (
                        SELECT 
                            sl.status::text,
                            sl.created as ts,
                            LAG(sl.status::text) OVER (ORDER BY sl.created DESC) as prev_status
                        FROM status_logs sl
                    ),
                    filtered_changes AS (
                        SELECT 
                            sp.status::text,
                            sp.ts
                        FROM status_with_prev sp
                        WHERE sp.prev_status IS NULL OR sp.status != sp.prev_status
                    ),
                    changes_with_duration AS (
                        SELECT 
                            fc.status::text,
                            fc.ts,
                            LEAD(fc.ts) OVER (ORDER BY fc.ts DESC) as next_ts
                        FROM filtered_changes fc
                    )
                    SELECT 
                        cd.status::text as status_value,
                        cd.ts as event_timestamp,
                        COALESCE(cd.ts - cd.next_ts, interval '0') as time_duration
                    FROM changes_with_duration cd
                    ORDER BY cd.ts DESC;
                END;
                $$ LANGUAGE plpgsql;
        """

    reverse_sql = "DROP FUNCTION IF EXISTS get_asset_timeline;"

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]