# Generated by Django 5.1.5 on 2025-02-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_add_get_asset_timeline_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremember',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coremember',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coremember',
            name='verification_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
