# Generated by Django 5.1.5 on 2025-02-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_coremember_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremember',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coremember',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
