# Generated by Django 5.1.5 on 2025-02-13 01:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_coremember_password_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('freelancer', 'Freelancer'), ('startup', 'Startup'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_clouds', models.PositiveIntegerField(help_text='Maximum number of clouds allowed')),
                ('max_assets', models.PositiveIntegerField(help_text='Maximum number of total assets allowed (servers + volumes + databases)')),
                ('monitoring_interval', models.PositiveIntegerField(help_text='Monitoring interval in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('log_retention_days', models.PositiveIntegerField(help_text='Number of days to retain logs', validators=[django.core.validators.MinValueValidator(1)])),
                ('enable_api_access', models.BooleanField(default=False)),
                ('enable_team_members', models.BooleanField(default=False)),
                ('max_team_members', models.PositiveIntegerField(default=1)),
                ('enable_custom_monitoring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'core_plan',
            },
        ),
        migrations.AddField(
            model_name='coreaccount',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreaccount',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='apps.coreplan'),
        ),
    ]
