# Generated by Django 5.1.5 on 2025-02-13 01:11
from django.db import migrations
from django.utils import timezone
from django.db import migrations


def create_initial_plans(apps, schema_editor):
    CorePlan = apps.get_model('apps', 'CorePlan')
    CoreAccount = apps.get_model('apps', 'CoreAccount')

    # Create Freelancer Plan
    freelancer = CorePlan.objects.create(
        name="Freelancer",
        type="freelancer",
        description="Perfect for individual developers and freelancers",
        max_clouds=1,
        max_assets=5,
        monitoring_interval=15,
        log_retention_days=7,
        enable_team_members=False,
        max_team_members=1,
        enable_custom_monitoring=False,
        enable_api_access=False,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )

    # Create Startup Plan
    startup = CorePlan.objects.create(
        name="Startup",
        type="startup",
        description="Ideal for growing teams and startups",
        max_clouds=3,
        max_assets=20,
        monitoring_interval=5,
        log_retention_days=30,
        enable_team_members=True,
        max_team_members=5,
        enable_custom_monitoring=True,
        enable_api_access=False,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )

    # Create Enterprise Plan
    enterprise = CorePlan.objects.create(
        name="Enterprise",
        type="enterprise",
        description="For large organizations with advanced needs",
        max_clouds=10,
        max_assets=100,
        monitoring_interval=1,
        log_retention_days=90,
        enable_team_members=True,
        max_team_members=20,
        enable_custom_monitoring=True,
        enable_api_access=True,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )

    # Assign Startup plan to all existing accounts
    CoreAccount.objects.filter(plan__isnull=True).update(
        plan=startup.id,
        updated_at=timezone.now()
    )


def reverse_initial_plans(apps, schema_editor):
    CorePlan = apps.get_model('apps', 'CorePlan')
    CoreAccount = apps.get_model('apps', 'CoreAccount')

    # First set all accounts' plan to null to avoid foreign key constraint issues
    CoreAccount.objects.all().update(plan=None)

    # Delete all plans
    CorePlan.objects.all().delete()




class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_coreplan_coreaccount_plan_expires_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_plans, reverse_initial_plans),
    ]
