# Generated by Django 5.1.5 on 2025-02-13 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_create_initial_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreaccount',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='apps.coreplan'),
        ),
    ]
