# Generated by Django 5.1.5 on 2025-02-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_alter_coreaccount_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corecloud',
            name='name',
        ),
        migrations.AlterField(
            model_name='corecloud',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clouds', to='apps.coreaccount'),
        ),
    ]
