# Generated by Django 5.1.5 on 2025-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_remove_corecloud_name_alter_corecloud_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreaccount',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coreaccount',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
