# Generated by Django 5.1.5 on 2025-02-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0044_coreaccount_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corecloud',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('delete', 'Delete'), ('invalid_auth', 'Invalid Authentication')], default='active', max_length=64),
        ),
    ]
