# Generated by Django 5.1.5 on 2025-02-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_alter_corecloud_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreplan',
            name='type',
            field=models.CharField(choices=[('hacker', 'Hacker'), ('startup', 'Startup'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
    ]
