# Generated by Django 5.1.5 on 2025-02-17 15:23

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_alter_coreplan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilOldCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('total_spend', models.FloatField(null=True)),
                ('plan', models.TextField()),
                ('invite_key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'utils_old_customer',
            },
        ),
    ]
