# Generated by Django 5.1.5 on 2025-02-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0047_utiloldcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utiloldcustomer',
            name='plan',
            field=models.TextField(null=True),
        ),
    ]
