# Generated by Django 5.1.5 on 2025-02-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0049_remove_utiloldcustomer_total_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='utiloldcustomer',
            name='invite_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted')], default='pending', max_length=64),
        ),
    ]
