# Generated by Django 5.1.5 on 2025-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0050_utiloldcustomer_invite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utiloldcustomer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
