# Generated by Django 5.1.5 on 2025-02-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0052_coretotpdevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corecloud',
            options={'verbose_name': 'Cloud', 'verbose_name_plural': 'Clouds'},
        ),
    ]
