# Generated by Django 5.1.6 on 2025-02-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0055_coreawsaccount_coreawsinstance_coreawsvolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreawsinstance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='apps.coreawsaccount'),
        ),
    ]
