# Generated by Django 5.1.6 on 2025-03-05 07:14

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0056_alter_coreawsinstance_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUpCloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=64)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcloud', to='apps.corecloud')),
            ],
            options={
                'db_table': 'core_upcloud_account',
            },
        ),
        migrations.CreateModel(
            name='CoreUpCloudServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='apps.coreupcloudaccount')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule')),
            ],
            options={
                'db_table': 'core_upcloud_server',
            },
        ),
        migrations.CreateModel(
            name='CoreUpCloudVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='apps.coreupcloudaccount')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.coreschedule')),
            ],
            options={
                'db_table': 'core_upcloud_volume',
            },
        ),
    ]
