# Generated by Django 5.1.6 on 2025-03-06 05:27

import uuid
from django.db import migrations, models


def generate_uuids_for_existing_records(apps, schema_editor):
    """Generate UUIDs for all existing records in the affected models"""
    models_to_update = [
        apps.get_model('apps', 'CoreAWSInstance'),
        apps.get_model('apps', 'CoreAWSVolume'),
        apps.get_model('apps', 'CoreDigitalOceanDatabase'),
        apps.get_model('apps', 'CoreDigitalOceanServer'),
        apps.get_model('apps', 'CoreDigitalOceanVolume'),
        apps.get_model('apps', 'CoreHetznerServer'),
        apps.get_model('apps', 'CoreHetznerVolume'),
        apps.get_model('apps', 'CoreUpcloudServer'),
        apps.get_model('apps', 'CoreUpcloudVolume'),
        apps.get_model('apps', 'CoreVultrDatabase'),
        apps.get_model('apps', 'CoreVultrServer'),
        apps.get_model('apps', 'CoreVultrVolume'),
    ]

    for model in models_to_update:
        for record in model.objects.all():
            record.uuid = uuid.uuid4()
            record.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('apps', '0058_corecloud_uuid'),
    ]

    operations = [
        # First add all UUID fields as nullable
        migrations.AddField(
            model_name='coreawsinstance',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='coreawsvolume',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceandatabase',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserver',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolume',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='corehetznerserver',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='corehetznervolume',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='coreupcloudserver',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='coreupcloudvolume',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='corevultrdatabase',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='corevultrserver',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='corevultrvolume',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),

        # Run function to populate UUIDs for existing records
        migrations.RunPython(generate_uuids_for_existing_records),

        # Now update all fields to be non-nullable with default UUID generator
        migrations.AlterField(
            model_name='coreawsinstance',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coreawsvolume',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceandatabase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanserver',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanvolume',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='corehetznerserver',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='corehetznervolume',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudserver',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudvolume',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='corevultrdatabase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='corevultrserver',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='corevultrvolume',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]