# Generated by Django 5.1.6 on 2025-03-06 05:39

import uuid
from django.db import migrations, models


def generate_uuids_for_existing_schedules(apps, schema_editor):
    """Generate UUIDs for all existing CoreSchedule records"""
    CoreSchedule = apps.get_model('apps', 'CoreSchedule')
    for schedule in CoreSchedule.objects.all():
        schedule.uuid = uuid.uuid4()
        schedule.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('apps', '0059_coreawsinstance_uuid_coreawsvolume_uuid_and_more'),
    ]

    operations = [
        # First add the UUID field as nullable
        migrations.AddField(
            model_name='coreschedule',
            name='uuid',
            field=models.UUIDField(null=True, blank=True),
        ),

        # Run function to populate UUIDs for existing records
        migrations.RunPython(generate_uuids_for_existing_schedules),

        # Now update the field to be non-nullable with default UUID generator
        migrations.AlterField(
            model_name='coreschedule',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]