# Generated by Django 5.1.7 on 2025-03-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0060_coreschedule_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreawsinstance',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='coreawsvolume',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceandatabase',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceanserver',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceanvolume',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corehetznerserver',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corehetznervolume',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='coreupcloudserver',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='coreupcloudvolume',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corevultrdatabase',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corevultrserver',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='corevultrvolume',
            name='schedule',
        ),
        migrations.AddField(
            model_name='coreawsinstance',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreawsvolume',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceandatabase',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanserver',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coredigitaloceanvolume',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corehetznerserver',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corehetznervolume',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreupcloudserver',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreupcloudvolume',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corevultrdatabase',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corevultrserver',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corevultrvolume',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
