# Generated by Django 5.1.7 on 2025-03-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0061_remove_coreawsinstance_schedule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreSchedule',
        ),
    ]
