# Generated by Django 5.2.3 on 2025-06-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0065_rename_aws_database_to_rds_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreawsinstance',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsrdsdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceandatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznerserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznervolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodeserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodevolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database')], max_length=64, null=True),
        ),
    ]
