# Generated by Django 5.2.3 on 2025-06-22 22:20

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0066_add_rds_database_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreawsinstance',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsrdsdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceandatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznerserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznervolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodeserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodevolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='CoreAWSLambda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('aws_schedule_arn', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lambda_functions', to='apps.coreawsaccount')),
            ],
            options={
                'db_table': 'core_aws_lambda',
            },
        ),
    ]
