# Generated by Django 4.2.7 on 2024-01-15 12:00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0074_add_aws_security_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreAWSECSService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('metadata', models.JSONField(default=dict)),
                ('notification_emails', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=30)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], default='ecs_service', max_length=30)),
                ('aws_schedule_arn', models.CharField(blank=True, max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecs_services', to='apps.coreawsaccount')),
            ],
            options={
                'db_table': 'core_aws_ecs_service',
            },
        ),
        migrations.CreateModel(
            name='CoreAWSECSTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('metadata', models.JSONField(default=dict)),
                ('notification_emails', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=30)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], default='ecs_task', max_length=30)),
                ('aws_schedule_arn', models.CharField(blank=True, max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecs_tasks', to='apps.coreawsaccount')),
            ],
            options={
                'db_table': 'core_aws_ecs_task',
            },
        ),
    ] 