# Generated by Django 5.2.3 on 2025-06-23 19:06

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0075_add_aws_ecs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreawsacmcertificate',
            name='aws_eventbridge_rule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawsecsservice',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='coreawsecstask',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='coreawselasticip',
            name='aws_eventbridge_rule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawsloadbalancer',
            name='aws_eventbridge_rule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawssecuritygroup',
            name='aws_eventbridge_rule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawssnapshot',
            name='aws_eventbridge_rule_arn',
        ),
        migrations.AddField(
            model_name='coreawsacmcertificate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreawsecsservice',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='coreawsecsservice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreawsecstask',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='coreawsecstask',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreawselasticip',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreawsloadbalancer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreawssecuritygroup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coreawssnapshot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='monitoring',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawsdynamodb',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='monitoring',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='monitoring',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='monitoring',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawsinstance',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawslambda',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='monitoring',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawsrdsdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawss3bucket',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='monitoring',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='aws_schedule_arn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='monitoring',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='notification_emails',
            field=models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes'),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coreawsvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceandatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznerserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznervolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodeserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodevolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('elastic_ip', 'Elastic IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
    ]
