# Generated by Django 6.0.5 on 2026-07-26 08:59

import apps.console.plan.models
import django.db.models.deletion
from django.db import migrations, models


def create_default_plan(apps, schema_editor):
    """Seed the default plan for self-hosted instances."""
    CorePlan = apps.get_model('apps', 'CorePlan')
    CorePlan.objects.get_or_create(
        type='selfhosted',
        defaults={
            'name': 'Self-Hosted',
            'description': 'Default plan for self-hosted CloudMoo instances.',
            'max_clouds': 1000,
            'max_assets': 10000,
            'monitoring_interval': 1,
            'log_retention_days': 30,
            'enable_api_access': True,
            'enable_team_members': True,
            'max_team_members': 1000,
            'enable_custom_monitoring': True,
        },
    )


def remove_default_plan(apps, schema_editor):
    CorePlan = apps.get_model('apps', 'CorePlan')
    CorePlan.objects.filter(type='selfhosted').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0077_fix_aws_account_null_regions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilOldCustomer',
        ),
        migrations.DeleteModel(
            name='WaitingList',
        ),
        migrations.RemoveField(
            model_name='coreaccount',
            name='plan_expires_at',
        ),
        migrations.RemoveField(
            model_name='coreaccount',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='coreaccount',
            name='stripe_subscription_id',
        ),
        migrations.AlterField(
            model_name='coreaccount',
            name='plan',
            field=models.ForeignKey(default=apps.console.plan.models.get_default_plan_id, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='apps.coreplan'),
        ),
        migrations.AlterField(
            model_name='coreplan',
            name='type',
            field=models.CharField(choices=[('selfhosted', 'Self-Hosted'), ('hacker', 'Hacker'), ('startup', 'Startup'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
        migrations.RunPython(create_default_plan, remove_default_plan),
    ]
