# Generated by Django 6.0.5 on 2026-07-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0078_delete_utiloldcustomer_delete_waitinglist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatusEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_key', models.CharField(db_index=True, max_length=80)),
                ('account_id', models.IntegerField(db_index=True)),
                ('asset_id', models.IntegerField()),
                ('provider', models.CharField(max_length=32)),
                ('asset_type', models.CharField(max_length=32)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('text_body', models.TextField()),
                ('html_body', models.TextField()),
                ('status_previous', models.CharField(blank=True, default='', max_length=64)),
                ('status_current', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'asset_status_email',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='coreawsacmcertificate',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawsdynamodb',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawsecsservice',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawsecstask',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawselasticip',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawsinstance',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawslambda',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawsloadbalancer',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawsrdsdatabase',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawss3bucket',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawssecuritygroup',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawssnapshot',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreawsvolume',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corecloud',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceandatabase',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceanserver',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coredigitaloceanvolume',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corehetznerserver',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corehetznervolume',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corelinodeserver',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corelinodevolume',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreupcloudserver',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='coreupcloudvolume',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corevultrdatabase',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corevultrserver',
            name='aws_schedule_arn',
        ),
        migrations.RemoveField(
            model_name='corevultrvolume',
            name='aws_schedule_arn',
        ),
        migrations.CreateModel(
            name='AssetStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_key', models.CharField(db_index=True, max_length=80)),
                ('account_id', models.IntegerField(db_index=True)),
                ('provider', models.CharField(max_length=32)),
                ('asset_type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('metadata_changes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_status_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset_key', '-timestamp'], name='asset_statu_asset_k_9bcb51_idx'), models.Index(fields=['account_id', '-timestamp'], name='asset_statu_account_d722ec_idx')],
            },
        ),
    ]
