# Generated by Django 6.0.5 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0079_assetstatusemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMonitoringState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_key', models.CharField(max_length=80, unique=True)),
                ('account_id', models.IntegerField(db_index=True)),
                ('provider', models.CharField(max_length=32)),
                ('asset_type', models.CharField(max_length=32)),
                ('last_checked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_status', models.CharField(blank=True, default='', max_length=64)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_change_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_monitoring_state',
                'indexes': [
                    models.Index(fields=['account_id', 'last_checked_at'], name='asset_monit_account_5e31b0_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='assetstatusemail',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assetstatusemail',
            name='delivery_key',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assetstatusemail',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='assetstatusemail',
            name='event_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assetstatusemail',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assetstatusemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
