# Generated by Django 6.0.5 on 2026-08-02 12:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0084_rename_status_email_delivery_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='coredigitaloceanaccount',
            name='spaces_access_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='coredigitaloceanaccount',
            name='spaces_region',
            field=models.CharField(blank=True, default='nyc3', max_length=64),
        ),
        migrations.AddField(
            model_name='coredigitaloceanaccount',
            name='spaces_secret_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsdynamodb',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsinstance',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawslambda',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsrdsdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawss3bucket',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceandatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznerserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznervolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodeserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodevolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_app',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_backup',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanContainerRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_registries', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_container_registry',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanFirewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewalls', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_firewall',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanLoadBalancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_balancers', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_load_balancer',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanReservedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_ips', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_reserved_ip',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_snapshot',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_space',
            },
        ),
    ]
