# Generated by Django 6.0.5 on 2026-08-02 15:09

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0085_add_digitalocean_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreawsacmcertificate',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsdynamodb',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecsservice',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsecstask',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawselasticip',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsinstance',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawslambda',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsloadbalancer',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsrdsdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawss3bucket',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawssecuritygroup',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawssnapshot',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreawsvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanapp',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanbackup',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceancontainerregistry',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceandatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanfirewall',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanloadbalancer',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanreservedip',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceansnapshot',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanspace',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coredigitaloceanvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznerserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corehetznervolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodeserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corelinodevolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coreupcloudvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrdatabase',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrserver',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='corevultrvolume',
            name='type',
            field=models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanCDNEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdn_endpoints', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_cdn_endpoint',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_certificate',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanDNSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_dns_record',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_domain',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanKubernetesCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kubernetes_clusters', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_kubernetes_cluster',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanKubernetesNodePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kubernetes_node_pools', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_kubernetes_node_pool',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanVPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpcs', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_vpc',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanVPCNATGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpc_nat_gateways', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_vpc_nat_gateway',
            },
        ),
        migrations.CreateModel(
            name='CoreDigitalOceanVPCPeering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vpc', 'VPC'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpc_peerings', to='apps.coredigitaloceanaccount')),
            ],
            options={
                'db_table': 'core_digitalocean_vpc_peering',
            },
        ),
    ]
