# Generated by Django 6.0.5 on 2026-08-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0087_alter_coreawsacmcertificate_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coreawslightsailalarm',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_alarm_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailautosnapshot',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_auto_snapshot_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailbucket',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_bucket_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailcertificate',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_certificate_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailcontainerdeployment',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_container_deployment_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailcontainerimage',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_container_image_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailcontainerservice',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_container_service_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsaildatabase',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_database_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsaildatabasesnapshot',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_database_snapshot_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsaildisk',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_disk_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsaildisksnapshot',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_disk_snapshot_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsaildistribution',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_distribution_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsaildnsrecord',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_dns_record_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsaildomain',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_domain_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailinstance',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_instance_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailinstancesnapshot',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_instance_snapshot_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailloadbalancer',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_load_balancer_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailoperation',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_operation_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='coreawslightsailstaticip',
            constraint=models.UniqueConstraint(fields=('owner', 'unique_id'), name='aws_ls_static_ip_uid_uniq'),
        ),
    ]
