# Generated by Django 6.0.5 on 2026-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0094_seed_cloud_service_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreupcloudaccount',
            name='api_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coreupcloudaccount',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='coreupcloudaccount',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
