# Generated by Django 6.0.5 on 2026-08-13 16:51

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


# Seed the Oracle Cloud provider row so the "Connect" page offers it on
# installs that run migrations without setup_test_accounts.
def seed_oracle_provider(apps, schema_editor):
    CoreCloudServiceProvider = apps.get_model("apps", "CoreCloudServiceProvider")
    CoreCloudServiceProvider.objects.update_or_create(
        code="oracle",
        defaults={
            "name": "Oracle Cloud",
            "position": 7,
            "image": "console/images/clouds/oracle.svg",
            "status": "active",
        },
    )


def unseed_oracle_provider(apps, schema_editor):
    CoreCloudServiceProvider = apps.get_model("apps", "CoreCloudServiceProvider")
    CoreCloudServiceProvider.objects.filter(code="oracle").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0095_coreupcloudaccount_api_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreOracleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=64)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tenancy_ocid', models.CharField(blank=True, default='', max_length=255)),
                ('user_ocid', models.CharField(blank=True, default='', max_length=255)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=255)),
                ('private_key', models.TextField(blank=True, default='')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oracle', to='apps.corecloud')),
            ],
            options={
                'db_table': 'core_oracle_account',
            },
        ),
        migrations.CreateModel(
            name='CoreOracleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vultr_bare_metal', 'Vultr Bare Metal'), ('vultr_block_snapshot', 'Vultr Block Snapshot'), ('vultr_vfs', 'Vultr Virtual File System'), ('vultr_storage_gateway', 'Vultr Storage Gateway'), ('vultr_bandwidth_metric', 'Vultr Bandwidth Metric'), ('vultr_registry_repository', 'Vultr Registry Repository'), ('vultr_registry_artifact', 'Vultr Registry Artifact'), ('vultr_inference', 'Vultr Inference Endpoint'), ('vultr_firewall_rule', 'Vultr Firewall Rule'), ('vultr_storage_cluster', 'Vultr Storage Cluster'), ('vultr_storage_tier', 'Vultr Storage Tier'), ('vultr_plan', 'Vultr Plan'), ('vultr_region', 'Vultr Region'), ('vultr_compute_plan', 'Vultr Compute Plan'), ('vultr_account_log', 'Vultr Account Log'), ('vultr_status_incident', 'Vultr Status Incident'), ('primary_ip', 'Primary IP'), ('floating_ip', 'Floating IP'), ('network', 'Network'), ('placement_group', 'Placement Group'), ('image', 'Image'), ('location', 'Location'), ('datacenter', 'Datacenter'), ('server_type', 'Server Type'), ('iso', 'ISO'), ('ssh_key', 'SSH Key'), ('load_balancer_type', 'Load Balancer Type'), ('zone', 'DNS Zone'), ('rrset', 'DNS RRSet'), ('action', 'Provider Action'), ('aws_cloudwatch_alarm', 'AWS CloudWatch Alarm'), ('aws_cloudwatch_metric', 'AWS CloudWatch Metric'), ('aws_log_group', 'AWS Log Group'), ('aws_ecr_repository', 'AWS ECR Repository'), ('aws_ecr_image', 'AWS ECR Image'), ('aws_ecs_task_definition', 'AWS ECS Task Definition'), ('aws_ecs_deployment', 'AWS ECS Deployment'), ('aws_eks_cluster', 'AWS EKS Cluster'), ('aws_eks_node_group', 'AWS EKS Node Group'), ('aws_eks_addon', 'AWS EKS Add-on'), ('aws_eks_fargate_profile', 'AWS EKS Fargate Profile'), ('aws_apprunner_service', 'AWS App Runner Service'), ('aws_apprunner_deployment', 'AWS App Runner Deployment'), ('aws_route53_zone', 'AWS Route 53 Zone'), ('aws_route53_record', 'AWS Route 53 Record'), ('aws_cloudfront_distribution', 'AWS CloudFront Distribution'), ('aws_cloudfront_origin_access_control', 'AWS CloudFront Origin Access Control'), ('aws_waf_web_acl', 'AWS WAF Web ACL'), ('aws_global_accelerator', 'AWS Global Accelerator'), ('aws_backup_vault', 'AWS Backup Vault'), ('aws_backup_plan', 'AWS Backup Plan'), ('aws_backup_recovery_point', 'AWS Backup Recovery Point'), ('aws_backup_job', 'AWS Backup Job'), ('aws_backup_copy_job', 'AWS Backup Copy Job'), ('aws_rds_cluster', 'AWS RDS Cluster'), ('aws_elasticache_cluster', 'AWS ElastiCache Cluster'), ('aws_elasticache_replication_group', 'AWS ElastiCache Replication Group'), ('aws_elasticache_serverless_cache', 'AWS ElastiCache Serverless Cache'), ('aws_memorydb_cluster', 'AWS MemoryDB Cluster'), ('aws_opensearch_domain', 'AWS OpenSearch Domain'), ('aws_efs_file_system', 'AWS EFS File System'), ('aws_fsx_file_system', 'AWS FSx File System'), ('aws_apigateway_rest_api', 'AWS API Gateway REST API'), ('aws_apigateway_v2_api', 'AWS API Gateway v2 API'), ('aws_eventbridge_bus', 'AWS EventBridge Bus'), ('aws_eventbridge_rule', 'AWS EventBridge Rule'), ('aws_eventbridge_schedule', 'AWS EventBridge Schedule'), ('aws_eventbridge_pipe', 'AWS EventBridge Pipe'), ('aws_sns_topic', 'AWS SNS Topic'), ('aws_sqs_queue', 'AWS SQS Queue'), ('aws_stepfunctions_state_machine', 'AWS Step Functions State Machine'), ('aws_athena_workgroup', 'AWS Athena Workgroup'), ('aws_athena_data_catalog', 'AWS Athena Data Catalog'), ('aws_cloudformation_stack', 'AWS CloudFormation Stack'), ('aws_elastic_beanstalk_application', 'AWS Elastic Beanstalk Application'), ('aws_elastic_beanstalk_environment', 'AWS Elastic Beanstalk Environment'), ('aws_codebuild_project', 'AWS CodeBuild Project'), ('aws_codebuild_build', 'AWS CodeBuild Build'), ('aws_codepipeline_pipeline', 'AWS CodePipeline Pipeline'), ('aws_codepipeline_execution', 'AWS CodePipeline Execution'), ('aws_iam_user', 'AWS IAM User'), ('aws_iam_role', 'AWS IAM Role'), ('aws_iam_policy', 'AWS IAM Policy'), ('aws_kms_key', 'AWS KMS Key'), ('aws_kms_alias', 'AWS KMS Alias'), ('aws_cloudtrail_trail', 'AWS CloudTrail Trail'), ('aws_config_rule', 'AWS Config Rule'), ('aws_config_recorder', 'AWS Config Recorder'), ('aws_guardduty_detector', 'AWS GuardDuty Detector'), ('aws_security_hub', 'AWS Security Hub'), ('aws_inspector', 'AWS Inspector'), ('aws_macie', 'AWS Macie'), ('aws_firewall_manager_policy', 'AWS Firewall Manager Policy'), ('aws_secrets_manager_secret', 'AWS Secrets Manager Secret'), ('aws_ssm_parameter', 'AWS SSM Parameter'), ('aws_health_event', 'AWS Health Event'), ('aws_trusted_advisor_check', 'AWS Trusted Advisor Check'), ('aws_cost_explorer_signal', 'AWS Cost Explorer Signal'), ('aws_cost_anomaly_monitor', 'AWS Cost Anomaly Monitor'), ('aws_cost_anomaly_subscription', 'AWS Cost Anomaly Subscription'), ('aws_cost_anomaly', 'AWS Cost Anomaly'), ('vpc', 'VPC'), ('subnet', 'Subnet'), ('route_table', 'Route Table'), ('internet_gateway', 'Internet Gateway'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('network_acl', 'Network ACL'), ('network_interface', 'Network Interface'), ('transit_gateway_attachment', 'Transit Gateway Attachment'), ('vpn_connection', 'VPN Connection'), ('flow_log', 'Flow Log'), ('auto_scaling_group', 'Auto Scaling Group'), ('launch_template', 'Launch Template'), ('ami', 'AMI'), ('ebs_attachment', 'EBS Attachment'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate'), ('lightsail_instance', 'Lightsail Instance'), ('lightsail_disk', 'Lightsail Disk'), ('lightsail_instance_snapshot', 'Lightsail Instance Snapshot'), ('lightsail_disk_snapshot', 'Lightsail Disk Snapshot'), ('lightsail_static_ip', 'Lightsail Static IP'), ('lightsail_database', 'Lightsail Database'), ('lightsail_database_snapshot', 'Lightsail Database Snapshot'), ('lightsail_load_balancer', 'Lightsail Load Balancer'), ('lightsail_certificate', 'Lightsail Certificate'), ('lightsail_bucket', 'Lightsail Bucket'), ('lightsail_distribution', 'Lightsail Distribution'), ('lightsail_domain', 'Lightsail DNS Zone'), ('lightsail_dns_record', 'Lightsail DNS Record'), ('lightsail_container_service', 'Lightsail Container Service'), ('lightsail_container_deployment', 'Lightsail Container Deployment'), ('lightsail_container_image', 'Lightsail Container Image'), ('lightsail_alarm', 'Lightsail Alarm'), ('lightsail_operation', 'Lightsail Operation'), ('lightsail_auto_snapshot', 'Lightsail Auto Snapshot')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='apps.coreoracleaccount')),
            ],
            options={
                'db_table': 'core_oracle_instance',
            },
        ),
        migrations.CreateModel(
            name='CoreOracleVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('metadata', models.JSONField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('monitoring', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('no_longer_exists', 'No Longer Exists')], default='active', max_length=64)),
                ('type', models.CharField(choices=[('server', 'Server'), ('volume', 'Volume'), ('database', 'Database'), ('rds_database', 'RDS Database'), ('lambda', 'Lambda Function'), ('dynamodb', 'DynamoDB Table'), ('s3_bucket', 'S3 Bucket'), ('acm_certificate', 'ACM Certificate'), ('snapshot', 'Snapshot'), ('backup', 'Backup'), ('elastic_ip', 'Elastic IP'), ('reserved_ip', 'Reserved IP'), ('load_balancer', 'Load Balancer'), ('security_group', 'Security Group'), ('firewall', 'Firewall'), ('app_platform', 'App Platform App'), ('object_storage', 'Object Storage'), ('container_registry', 'Container Registry'), ('ecs_service', 'ECS Service'), ('ecs_task', 'ECS Task'), ('kubernetes_cluster', 'Kubernetes Cluster'), ('kubernetes_node_pool', 'Kubernetes Node Pool'), ('vultr_bare_metal', 'Vultr Bare Metal'), ('vultr_block_snapshot', 'Vultr Block Snapshot'), ('vultr_vfs', 'Vultr Virtual File System'), ('vultr_storage_gateway', 'Vultr Storage Gateway'), ('vultr_bandwidth_metric', 'Vultr Bandwidth Metric'), ('vultr_registry_repository', 'Vultr Registry Repository'), ('vultr_registry_artifact', 'Vultr Registry Artifact'), ('vultr_inference', 'Vultr Inference Endpoint'), ('vultr_firewall_rule', 'Vultr Firewall Rule'), ('vultr_storage_cluster', 'Vultr Storage Cluster'), ('vultr_storage_tier', 'Vultr Storage Tier'), ('vultr_plan', 'Vultr Plan'), ('vultr_region', 'Vultr Region'), ('vultr_compute_plan', 'Vultr Compute Plan'), ('vultr_account_log', 'Vultr Account Log'), ('vultr_status_incident', 'Vultr Status Incident'), ('primary_ip', 'Primary IP'), ('floating_ip', 'Floating IP'), ('network', 'Network'), ('placement_group', 'Placement Group'), ('image', 'Image'), ('location', 'Location'), ('datacenter', 'Datacenter'), ('server_type', 'Server Type'), ('iso', 'ISO'), ('ssh_key', 'SSH Key'), ('load_balancer_type', 'Load Balancer Type'), ('zone', 'DNS Zone'), ('rrset', 'DNS RRSet'), ('action', 'Provider Action'), ('aws_cloudwatch_alarm', 'AWS CloudWatch Alarm'), ('aws_cloudwatch_metric', 'AWS CloudWatch Metric'), ('aws_log_group', 'AWS Log Group'), ('aws_ecr_repository', 'AWS ECR Repository'), ('aws_ecr_image', 'AWS ECR Image'), ('aws_ecs_task_definition', 'AWS ECS Task Definition'), ('aws_ecs_deployment', 'AWS ECS Deployment'), ('aws_eks_cluster', 'AWS EKS Cluster'), ('aws_eks_node_group', 'AWS EKS Node Group'), ('aws_eks_addon', 'AWS EKS Add-on'), ('aws_eks_fargate_profile', 'AWS EKS Fargate Profile'), ('aws_apprunner_service', 'AWS App Runner Service'), ('aws_apprunner_deployment', 'AWS App Runner Deployment'), ('aws_route53_zone', 'AWS Route 53 Zone'), ('aws_route53_record', 'AWS Route 53 Record'), ('aws_cloudfront_distribution', 'AWS CloudFront Distribution'), ('aws_cloudfront_origin_access_control', 'AWS CloudFront Origin Access Control'), ('aws_waf_web_acl', 'AWS WAF Web ACL'), ('aws_global_accelerator', 'AWS Global Accelerator'), ('aws_backup_vault', 'AWS Backup Vault'), ('aws_backup_plan', 'AWS Backup Plan'), ('aws_backup_recovery_point', 'AWS Backup Recovery Point'), ('aws_backup_job', 'AWS Backup Job'), ('aws_backup_copy_job', 'AWS Backup Copy Job'), ('aws_rds_cluster', 'AWS RDS Cluster'), ('aws_elasticache_cluster', 'AWS ElastiCache Cluster'), ('aws_elasticache_replication_group', 'AWS ElastiCache Replication Group'), ('aws_elasticache_serverless_cache', 'AWS ElastiCache Serverless Cache'), ('aws_memorydb_cluster', 'AWS MemoryDB Cluster'), ('aws_opensearch_domain', 'AWS OpenSearch Domain'), ('aws_efs_file_system', 'AWS EFS File System'), ('aws_fsx_file_system', 'AWS FSx File System'), ('aws_apigateway_rest_api', 'AWS API Gateway REST API'), ('aws_apigateway_v2_api', 'AWS API Gateway v2 API'), ('aws_eventbridge_bus', 'AWS EventBridge Bus'), ('aws_eventbridge_rule', 'AWS EventBridge Rule'), ('aws_eventbridge_schedule', 'AWS EventBridge Schedule'), ('aws_eventbridge_pipe', 'AWS EventBridge Pipe'), ('aws_sns_topic', 'AWS SNS Topic'), ('aws_sqs_queue', 'AWS SQS Queue'), ('aws_stepfunctions_state_machine', 'AWS Step Functions State Machine'), ('aws_athena_workgroup', 'AWS Athena Workgroup'), ('aws_athena_data_catalog', 'AWS Athena Data Catalog'), ('aws_cloudformation_stack', 'AWS CloudFormation Stack'), ('aws_elastic_beanstalk_application', 'AWS Elastic Beanstalk Application'), ('aws_elastic_beanstalk_environment', 'AWS Elastic Beanstalk Environment'), ('aws_codebuild_project', 'AWS CodeBuild Project'), ('aws_codebuild_build', 'AWS CodeBuild Build'), ('aws_codepipeline_pipeline', 'AWS CodePipeline Pipeline'), ('aws_codepipeline_execution', 'AWS CodePipeline Execution'), ('aws_iam_user', 'AWS IAM User'), ('aws_iam_role', 'AWS IAM Role'), ('aws_iam_policy', 'AWS IAM Policy'), ('aws_kms_key', 'AWS KMS Key'), ('aws_kms_alias', 'AWS KMS Alias'), ('aws_cloudtrail_trail', 'AWS CloudTrail Trail'), ('aws_config_rule', 'AWS Config Rule'), ('aws_config_recorder', 'AWS Config Recorder'), ('aws_guardduty_detector', 'AWS GuardDuty Detector'), ('aws_security_hub', 'AWS Security Hub'), ('aws_inspector', 'AWS Inspector'), ('aws_macie', 'AWS Macie'), ('aws_firewall_manager_policy', 'AWS Firewall Manager Policy'), ('aws_secrets_manager_secret', 'AWS Secrets Manager Secret'), ('aws_ssm_parameter', 'AWS SSM Parameter'), ('aws_health_event', 'AWS Health Event'), ('aws_trusted_advisor_check', 'AWS Trusted Advisor Check'), ('aws_cost_explorer_signal', 'AWS Cost Explorer Signal'), ('aws_cost_anomaly_monitor', 'AWS Cost Anomaly Monitor'), ('aws_cost_anomaly_subscription', 'AWS Cost Anomaly Subscription'), ('aws_cost_anomaly', 'AWS Cost Anomaly'), ('vpc', 'VPC'), ('subnet', 'Subnet'), ('route_table', 'Route Table'), ('internet_gateway', 'Internet Gateway'), ('vpc_peering', 'VPC Peering'), ('nat_gateway', 'NAT Gateway'), ('network_acl', 'Network ACL'), ('network_interface', 'Network Interface'), ('transit_gateway_attachment', 'Transit Gateway Attachment'), ('vpn_connection', 'VPN Connection'), ('flow_log', 'Flow Log'), ('auto_scaling_group', 'Auto Scaling Group'), ('launch_template', 'Launch Template'), ('ami', 'AMI'), ('ebs_attachment', 'EBS Attachment'), ('domain', 'Domain'), ('dns_record', 'DNS Record'), ('cdn_endpoint', 'CDN Endpoint'), ('certificate', 'Certificate'), ('lightsail_instance', 'Lightsail Instance'), ('lightsail_disk', 'Lightsail Disk'), ('lightsail_instance_snapshot', 'Lightsail Instance Snapshot'), ('lightsail_disk_snapshot', 'Lightsail Disk Snapshot'), ('lightsail_static_ip', 'Lightsail Static IP'), ('lightsail_database', 'Lightsail Database'), ('lightsail_database_snapshot', 'Lightsail Database Snapshot'), ('lightsail_load_balancer', 'Lightsail Load Balancer'), ('lightsail_certificate', 'Lightsail Certificate'), ('lightsail_bucket', 'Lightsail Bucket'), ('lightsail_distribution', 'Lightsail Distribution'), ('lightsail_domain', 'Lightsail DNS Zone'), ('lightsail_dns_record', 'Lightsail DNS Record'), ('lightsail_container_service', 'Lightsail Container Service'), ('lightsail_container_deployment', 'Lightsail Container Deployment'), ('lightsail_container_image', 'Lightsail Container Image'), ('lightsail_alarm', 'Lightsail Alarm'), ('lightsail_operation', 'Lightsail Operation'), ('lightsail_auto_snapshot', 'Lightsail Auto Snapshot')], max_length=64, null=True)),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to notify for asset status changes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='apps.coreoracleaccount')),
            ],
            options={
                'db_table': 'core_oracle_volume',
            },
        ),
        migrations.RunPython(seed_oracle_provider, unseed_oracle_provider),
    ]
