# Generated by Django 6.0.5 on 2026-08-14 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0096_oracle_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cloud_uuid', models.UUIDField(db_index=True)),
                ('cloud_id', models.IntegerField(db_index=True)),
                ('account_id', models.IntegerField(db_index=True)),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('finalizing', 'Finalizing'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('families_total', models.PositiveIntegerField(default=0)),
                ('families_done', models.JSONField(blank=True, default=list)),
                ('family_errors', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cloud_sync_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['cloud_uuid', 'status', '-started_at'], name='cloud_sync__cloud_u_5f537a_idx')],
            },
        ),
    ]
